# Generated by Django 3.2.4 on 2021-06-20 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='TopDownRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='down', to='assets.asset')),
                ('top', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top', to='assets.asset')),
            ],
        ),
    ]
