# Generated by Django 3.2.4 on 2021-07-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20210701_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='first_angle',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='second_angle',
        ),
        migrations.AddField(
            model_name='relation',
            name='angle',
            field=models.IntegerField(default=0, verbose_name='Angle'),
            preserve_default=False,
        ),
    ]
