# Generated by Django 3.2.4 on 2021-07-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20210701_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='angle',
        ),
        migrations.AddField(
            model_name='relation',
            name='first_angle',
            field=models.IntegerField(default=0, verbose_name='First angle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='second_angle',
            field=models.IntegerField(default=0, verbose_name='Second angle'),
            preserve_default=False,
        ),
    ]
