# Generated by Django 3.2.4 on 2021-07-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20210701_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='dim',
            new_name='direction',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='first_angle',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='second_angle',
        ),
        migrations.AddField(
            model_name='relation',
            name='angle',
            field=models.IntegerField(default=0, verbose_name='Аngle'),
            preserve_default=False,
        ),
    ]
