# Generated by Django 3.2.4 on 2021-07-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20210701_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='image',
        ),
    ]
