# Generated by Django 3.2.4 on 2021-07-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_remove_asset_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='allowedInAir',
            field=models.BooleanField(default=False, verbose_name='allowedInAir'),
        ),
        migrations.AddField(
            model_name='asset',
            name='allowedOnEdge',
            field=models.BooleanField(default=False, verbose_name='allowedOnEdge'),
        ),
        migrations.AddField(
            model_name='asset',
            name='allowedOnGround',
            field=models.BooleanField(default=False, verbose_name='allowedOnGround'),
        ),
    ]
