# Generated by Django 3.2.4 on 2021-07-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_asset_defaultangle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='allowedOnEdge',
        ),
    ]
