# Generated by Django 3.2.4 on 2021-07-30 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_remove_asset_allowedonedge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spinset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, verbose_name='status')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='spinset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spinset', to='assets.spinset'),
        ),
    ]
