# Generated by Django 3.2.4 on 2021-07-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_auto_20210730_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinset',
            name='path',
            field=models.CharField(default='', max_length=200, verbose_name='path'),
            preserve_default=False,
        ),
    ]
